export const GAMECARDS_LOADING = "GAMECARDS_LOADING";
export const ADD_GAMECARDS = "ADD_GAMECARDS";
export const GAMECARDS_FAILED = "GAMECARDS_FAILED";

export const SIMILARGAMES_LOADING = "SIMILARGAMES_LOADING";
export const ADD_SIMILARGAMES = "ADD_SIMILARGAMES";
export const SIMILARGAMES_FAILED = "SIMILARGAMES_FAILED";
